dictionary/urls.py
from django.conf.urls import patterns, include, url
from dictionary.views import varvar,add_var

 
urlpatterns = patterns('',
 
url(r'^var/$',varvar, name='varvar'),
url(r'^addvar/$',add_var, name='add_var'),
   
)

polls/urls.py
from django.conf.urls import patterns, url
from polls.views import ProjectsListView, ProjectsDetailView,ComponentsListView, project_view

urlpatterns = patterns('',
url(r'^$',ProjectsListView.as_view(), name='list1'),
url(r'^(?P<pk>\d+)/$', project_view),


)

test1/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from polls import views
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
admin.autodiscover()

urlpatterns = patterns('',
  
    url(r'^$', 'test1.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('registration.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^components/', include('components.urls')),
    #url(r'^components/','components.views.dictionary', name='dictionary'),
    url(r'^project/', include('project.urls')),
    url(r'^dictionary/', include('dictionary.urls')),
)




    

dictionary/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
import pytz
from django.shortcuts import redirect, render
#from django_enumfield import enum

class Project(models.Model):
    title = models.CharField(max_length=255)
    datetime = models.DateTimeField('date published')
    name = models.CharField(max_length=200)
    descr = models.CharField(max_length=255)
    content = models.TextField(max_length=10000)
    def _unicode_(self):
        return self.title
    def get_absolute_url(self):
	return "/polls/%i/" % self.id

class Component_type(models.Model):
    type_name = models.IntegerField()
    


class Components(models.Model):	
    #id_c = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    type_c = models.ForeignKey(Component_type) #enum.EnumField(Component_type, default=Component_type.Component_A)
    def _unicode_(self):
        return self.name

class Pvar1_var2(models.Model):
    p = models.FloatField()
    u = models.FloatField()
    
    
class Variants(models.Model):
    project = models.ForeignKey(Project)
    type_c = models.ForeignKey(Component_type)#type_c = enum.EnumField(Component_type, default=Component_type.Component_A)
    num = models.CharField(max_length=255)
    pvar = models.FloatField()
    def _unicode_(self):
        return self.name

class Pvar_var(models.Model):
    var1 = models.ForeignKey(Variants, related_name='var1')
    var2 = models.ForeignKey(Variants, related_name='var2')
    p = models.FloatField()
    
  
class Var_comp(models.Model):
    variants = models.ForeignKey(Variants)
    components = models.ForeignKey(Components)

# Create your models here.

dictionary/views.py
from django.template import RequestContext
from polls.models import Project,Variants
from polls.models import Pvar_var,Pvar1_var2
from polls.models import Component_type,Components
from django.views.generic import ListView, DetailView
from django.forms import ModelForm
from django.shortcuts import redirect
import random
import json
import codecs
from django.shortcuts import HttpResponse
from django.shortcuts import render

def varvar(request):
    model_p_vv = Pvar_var.objects.all()
    model_var = Variants.objects.all()
    errors = []
    form = {}
    if request.POST:
        form['type_var1'] = request.POST.get('type_var1')
        form['type_var2'] = request.POST.get('type_var2')
        form['p'] = request.POST.get('p')
        if not form['type_var1']:
            errors.append('error name')
        if not form['type_var2']:
            errors.append('error name')
        if not form['p']:
            errors.append('error name')        
        if not errors:
           
            model1 = Pvar_var(var1_id=form['type_var1'],var2_id=form['type_var2'],p=form['p'])
            model1.save()
       
        return render(request, 'polls/var.html', {'errors': errors, 'form':form, 'model_p_vv' : model_p_vv,'model_var' : model_var })
    return render(request, 'polls/var.html', {'errors': errors, 'model_p_vv' : model_p_vv,'model_var' : model_var })

def add_var(request):
    errors = []
    form = {}
    model_var_v = Variants.objects.all()
    model_com = Components.objects.all()
    data_1 = [{'t' : str(x.type_c.type_name), 'name' : x.name } for x in model_com]
    model_proj = Project.objects.all()
    model_vr = Component_type.objects.all()
    model_p = Pvar1_var2.objects.all()
    if request.POST:
        form['project_var'] = request.POST.get('project_var')
        form['name_var'] = request.POST.getlist('name_var')
        form['type_comp'] = request.POST.get('type_comp')
        form['var_project'] = request.POST.get('var_project')
        form['p'] = request.POST.get('p')
        if not form['name_var']:
            errors.append('error name')
        if not form['type_comp']:
            errors.append('error name')
        if not form['p']:
            errors.append('error name')        
        if not errors:
           
            model1 = Variants(project_id = form['var_project'],type_c_id=form['type_comp'],num=' + '.join(form['name_var']),pvar=form['p'])
            model1.save()
       
        return render(request, 'polls/var_add.html', {'errors': errors, 'form':form,'model_vr' : model_vr,'model_p' : model_p,'model_com' :model_com,'model_proj':model_proj,'model_var_v' : model_var_v, 'data_1' : data_1 })
    return render(request, 'polls/var_add.html', {'errors': errors,'model_vr' : model_vr,'model_p' : model_p,'model_com' :model_com,'model_proj':model_proj,'model_var_v' : model_var_v, 'data_1' : data_1})

    

polls/views.py
from django.template import RequestContext
from polls.models import Project,Pvar1_var2,Variants
from polls.models import Components
from polls.models import Component_type
from django.views.generic import ListView, DetailView
from django.forms import ModelForm
from django.shortcuts import render
import random
import json
from django.utils import simplejson
from django.shortcuts import HttpResponse

# Create your views here.
class ProjectsListView(ListView):
	model = Project

class ProjectsDetailView(DetailView):
	model = Project

class ComponentsListView(ListView):
	model = Components

def project_view(request, pk):
    model_variants = Variants.objects.all()
    model_p_u = Pvar1_var2.objects.all()
    data = [{"u":str(x.u*10), "sorned" : x.p} for  x in model_p_u]
    '''data = [     
            {"u": "23.34",  "sorned": 467},
            {"u": "24.37 ", "sorned": 646},
            {"u": "25.39",  "sorned":323},
            {"u": "26.56",  "sorned": 245},
            {"u": "27.89",  "sorned": 654}
           ]'''
    data.sort()
    project = Project.objects.filter(id=pk)[0]
    return render(request, 'polls/project_detail.html', {'plot_data' : simplejson.dumps(data), 'project' : project, 'model_variants' : model_variants })




  

media/templates/polls/components_list.html
{% extends "base.html" %}

{% block content %}

<div class="buttons-container" style="padding: 14px 19px;">
{% if user.is_active and user.is_staff %}
<a href="{% url 'project' %}"><button type="button" class="btn btn-success">Создать проект</button></a>{% endif %}   
<a href="{% url 'dictionary' %}"><button type="button" class="btn">Справочник</button></a>   
</div>    
</body>
<TABLE WIDTH=100%>
 <TR> 
  <TH VALIGN=TOP ALIGN=LEFT><form  action="" method="post">
        <label>Имя компонента:</label> 
        <input name="name" type="text" value="{{ form.name }}">
         <label>Тип:</label>
	<select name="type_components">
	{% for components in model %}
          <option value="{{components.id}}">{{components.type_name}}</option>
	{% endfor %}
	</select>
        <input class="btn info"  type="submit" value="Отправить">
        {% csrf_token %}
    </form></TH>
  <TH ALIGN=CENTER>
	{% for components1 in model11 %}
        <p>{{ components1.name }} | {{ components1.type_c.type_name }}<a href="{% url 'delete_comp' components1.id %}"> <span class="label label-important">удалить</span> </a></p>
	 
	{% endfor %}     
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
                <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}</TH>
 </TR>
</TABLE>

{% endblock %}

media/templates/polls/create_proj.html
<h1>Добавить project</h1>
    
<form enctype="multipart/form-data" action="" method="post" id="project_form"><input type="hidden" name="csrfmiddlewaretoken" value="kKS2yi3XQgw8FgzgLRT1V5ZcNESlm3fk">
<div>
  <fieldset class="module aligned ">
        <div class="form-row field-title">
            
                <div>
                    
                    
                        <label class="required" for="id_title">Title:</label>
                        
                            <input class="vTextField" id="id_title" maxlength="255" name="title" type="text">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-datetime">
            
            
                <div>
                    
                    
                        <label class="required" for="id_datetime_0">Date published:</label>
                        
                            <p class="datetime">Дата: <input class="vDateField" id="id_datetime_0" name="datetime_0" size="10" type="text"><span class="datetimeshortcuts">&nbsp;<a href="javascript:DateTimeShortcuts.handleCalendarQuickLink(0, 0);">Сегодня</a>&nbsp;|&nbsp;<a href="javascript:DateTimeShortcuts.openCalendar(0);" id="calendarlink0"><img src="./Добавить project   Project-Id-Version  django-core Report-Msgid-Bugs-To  POT-Creation-Date  2013-05-25 14 19+0200 PO-Revision-Date  2013-11-07 12 41+0000 Last-Translator  Алексей Борискин  sun.void@gmail.com  Language-Team  Rus_files/icon_calendar.gif" alt="Календарь"></a></span><br>Время: <input class="vTimeField" id="id_datetime_1" name="datetime_1" size="8" type="text"><span class="datetimeshortcuts">&nbsp;<a href="javascript:DateTimeShortcuts.handleClockQuicklink(0, new Date().strftime('%H:%M:%S'));">Сейчас</a>&nbsp;|&nbsp;<a href="javascript:DateTimeShortcuts.openClock(0);" id="clocklink0"><img src="./Добавить project   Project-Id-Version  django-core Report-Msgid-Bugs-To  POT-Creation-Date  2013-05-25 14 19+0200 PO-Revision-Date  2013-11-07 12 41+0000 Last-Translator  Алексей Борискин  sun.void@gmail.com  Language-Team  Rus_files/icon_clock.gif" alt="Часы"></a></span></p>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-name">
            
            
                <div>
                    
                    
                        <label class="required" for="id_name">Name:</label>
                        
                            <input class="vTextField" id="id_name" maxlength="200" name="name" type="text">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-descr">
            
            
                <div>
                    
                    
                        <label class="required" for="id_descr">Descr:</label>
                        
                            <input class="vTextField" id="id_descr" maxlength="255" name="descr" type="text">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-content">
            
            
                <div>
                    
                    
                        <label class="required" for="id_content">Content:</label>
                        
                            <textarea class="vLargeTextField" cols="40" id="id_content" name="content" rows="10"></textarea>
                        
                    
                    
                </div>
            
        </div>

media/templates/polls/dictionary.html
{% extends "base.html" %}

{% block content %}

<div class="buttons-container" style="padding: 14px 19px;">
{% if user.is_active and user.is_staff %}
<a href="{% url 'project' %}"><button type="button" class="btn btn-success">Создать проект</button></a>{% endif %}


   
    <a href="{% url 'list' %}"><button class="btn info">Справочник</button></a>
</div>{
	{% for components in object_list %}
          <p>{{ components.name }}</p>
	  <h6><p>{{ components.type_c.type_name }}</p></h6>
}

	{% empty %}
	<p>Пусто(((</p>
	{% endfor %}     
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
                <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
     
    <form  action="" method="post">
        <label>Имя компонента:</label> 
        <input name="name" type="text" value="{{ form.name }}">
         <label>Тип:</label>
	<select name="type_c">
	{% for components in object_list %}
          <option value="{{ components.type_c.type_name }}">{{ components.type_c.type_name }}</option>
}
	{% empty %}
	<p>Пусто(((</p>
	{% endfor %}
</select>
        <input  type="submit" value="Отправить">
        {% csrf_token %}
    </form>
</body>
 
</html>





{% endblock %}

media/templates/polls/project_detail.html
{% extends "base.html" %}

{% block content %}
<TABLE WIDTH=100%>
 <TR> 
  <TH VALIGN=TOP ALIGN=LEFT> <p>{{ project.datetime }}</p>  
        <h2>{{ project.title}} <a href="{% url 'delete_proj' project.id %}"> <span class="label label-important">удалить</span> </a></p></h2>
        
	<p>{{ project.content}}</p>
  </TH>
 {% if user.is_active and user.is_staff %}
 <script type="text/javascript">
     $(function () {
      tax_data = {{ plot_data|safe }};
      new Morris.Line({
        element: 'hero-graph',
        data: tax_data,
        xkey: 'u',
        ykeys: ['sorned'],
        labels: ['sorned']
      });
      $('.code-example').each(function (index, el) {
        eval($(el).text());
      });
    });
 </script>
  <TH ALIGN=RIRHT>
<div class="graph-container">
	<div class="caption">
	</div>
	<div id="hero-graph" class="graph"></div>
</div>
  </TH>
 </TR>
 <TR>
 <TH ALIGN=left>
 Варианты:<br>
     <select style="width: 100px;">
      <option>Filter 1</option>
      <option>Filter 2</option>
    </select><a href="{% url 'varvar' %}">  <button type="button" class="btn btn-success">Выбор вариантов</button></a> <a href="{% url 'add_var' %}">  <button type="button" class="btn btn-success">Создать вариант</button></a>
<BR>

<TABLE>
<CAPTION>Variants</CAPTION>
<TR>
<TH width=100>Имя компонента    </TH>
<TH width=30>  Тип    </TH>
<TH width=30>  Вероятность   </TH>
<TH width=30>   </TH>
</TR>
{% for variants in model_variants %}
<TR>
<TD width=30> {{variants.num}}</TD>
<TD ALIGN=CENTER >{{variants.type_c.type_name}}</TD>
<TD>{{variants.pvar}}</TD>	
<TD>  <a href="{% url 'delete_var' variants.id %}"> <span class="label label-important">удалить</span> </a></TD>
</TR>
{% endfor %}
</TABLE>
 
 </TR>
</TABLE>

<div id="disqus_thread"></div>
<script src="{{STATIC_URL}}js/jquery-1.7.2.min.js" type="text/javascript"> </script>
<script src="{{STATIC_URL}}js/raphael-min.js" type="text/javascript"> </script>
<script src="{{STATIC_URL}}js/morris.js" type="text/javascript"> </script>
<!--<script src="{{STATIC_URL}}js/script.js" type="text/javascript"> </script>-->

<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'localhosttestcs'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
</p>	
{% endif %}
{% endblock %}

media/templates/polls/project_list.html
{% extends "base.html" %}

{% block content %}
<div class="buttons-container" style="padding: 14px 19px;">{% if user.is_active and user.is_staff %}
<a href="{% url 'project' %}"><button type="button" class="btn btn-success">Создать проект</button></a>
<a href="{% url 'dictionary' %}"><button type="button" class="btn">Справочник</button></a>   
{% endif %}

 
</div>
<div class="well">

	{% for project in object_list %}
          <p>{{ project.datetime }}</p>
	  <h4><a href="{{project.get_absolute_url }}">{{ project.title }}</a></h4>
           <h6><p>{{ project.name}}</p><h6>
	  <h6><p>{{ project.descr }}</p></h6>
____________________________________________________________________________________________________
	{% empty %}
	<p>Пусто(((</p>
	{% endfor %}<br>
</div>
<ul class="pager">
  <li class="previous">
    <a href="#">&larr; Назад</a>
  </li>
  <li class="next">
    <a href="#">Вперед &rarr;</a>
  </li>
</ul>
{% endblock %}

media/templates/polls/var.html
{% extends "base.html" %}

{% block content %}
<TABLE WIDTH=100%>
 <TR> 
  <TH VALIGN=TOP ALIGN=Middle>
  <form action="" method="post">         {% csrf_token %}

        <label>Вариант1:</label>
	<select name="type_var1">
	{% for var in model_var %}
          <option value="{{var.id}}">{{var.num}}</option>
	{% endfor %}
	</select>
	<label>Вариант2:</label>
	<select name="type_var2">
	{% for var2 in model_var%}
          <option value="{{var2.id}}">{{var2.num}}</option>
	{% endfor %}
	</select>
	<label>Вероятность</label> 
        <input name="p" type="text" value="{{ p }}"><br>
        <input class="btn info"  type="submit" value="Отправить"></form>
    </form>
  </TH>
  <TH ALIGN=CENTER>
	</TH>
 </TR>
</TABLE>
{% endblock %}

media/templates/polls/var3.html
     {% extends "base.html" %}

{% block content %}
      <form action="" method="post">
        <label>Вариант1:</label>
	<select name="type_var1">
	{% for var in model_var %}
          <option value="{{var.num}}">{{var.num}}</option>
	{% endfor %}
	</select>
	<label>Вариант2:</label>
	<select name="type_var2">
	{% for var2 in model_var%}
          <option value="{{var2.num}}">{{var2.num}}</option>
	{% endfor %}
	</select>
	<label>Вероятность</label> 
        <input name="p" type="text" value="{{ p }}">
        <input class="btn info"  type="submit" value="Отправить"></form>
        {% csrf_token %}
        {% endblock %}

media/templates/polls/var_add.html
{% extends "base.html" %}

{% block content %}


<script charset="utf-8">
$(document).ready(function() {
    /*$('#btn-add').click(function(){
        $('#select-from option:selected').each( function() {
                $('#select-to').append("<option value='"+$(this).val()+"'>"+$(this).text()+"</option>");
            $(this).remove();
        });
    });
    $('#btn-remove').click(function(){
        $('#select-to option:selected').each( function() {
            $('#select-from').append("<option value='"+$(this).val()+"'>"+$(this).text()+"</option>");
            $(this).remove();
        });
    });
    $('#btn-up').bind('click', function() {
        $('#select-to option:selected').each( function() {
            var newPos = $('#select-to option').index(this) - 1;
            if (newPos > -1) {
                $('#select-to option').eq(newPos).before("<option value='"+$(this).val()+"' selected='selected'>"+$(this).text()+"</option>");
                $(this).remove();
            }
        });
    });
    $('#btn-down').bind('click', function() {
        var countOptions = $('#select-to option').size();
        $('#select-to option:selected').each( function() {
            var newPos = $('#select-to option').index(this) + 1;
            if (newPos < countOptions) {
                $('#select-to option').eq(newPos).after("<option value='"+$(this).val()+"' selected='selected'>"+$(this).text()+"</option>");
                $(this).remove();
            }
        });
    });*/
    components = {{ data_1 | safe }}
    /*[
        {'t':0, 'name':'name1'},
        {'t':1, 'name':'name2'},
        {'t':2, 'name':'name3'},
        {'t':3, 'name':'name4'},
        {'t':3, 'name':'name5'}
    ]*/
    $('[name="type_comp"]').change(function() {
        $('[name="name_var"] > option').each( function() {
            $('option[value="' + $(this).val() +  '"]', $('[name="name_var"]')).remove();
            //console.log($(this).val());
            //$('#select-from').append("<option value='"+$(this).val()+"'>"+$(this).text()+"</option>");
            //$(this).remove();
        });
        //console.log($('[name="type_comp"]').find(":selected").text());
        to_add = components.filter(function (vr){
            return vr['t'] == $('[name="type_comp"]').find(":selected").text();
        });
        //console.log(to_add)
        to_add.map(function (x,y,z){
            $('[name="name_var"]').append('<option value="' + x['name'] + '">' + x['name'] + '</option>').multiselect('rebuild');
            //console.log(x);
            //console.log(y);
            //console.log(z);
        })
        //$('[name="name_var"]').append('<option value="123">312</option>').multiselect('rebuild');
        $('[name="name_var"]').multiselect('destroy');
        $('[name="name_var"]').multiselect();
        $('[name="name_var"]').multiselect().trigger('reset');
        //console.log($('[name="name_var"]'));  
    });
    //$('.multiselect').multiselect();
    $('[name="name_var"]').append('<option value="123">312</option>').multiselect('rebuild');;
    //$('.multiselect').multiselect();
    
});
</script>

<script type="text/javascript" charset="utf-8">
  //$(document).ready(function() {
  //  $('.multiselect').multiselect();
  //});
</script>
<TABLE WIDTH=100%>
 <TR> 
  <TH VALIGN=TOP ALIGN=Middle>
  <form action="" method="post">         {% csrf_token %}
   
        <label>Тип компонента:</label>
	<select name="type_comp">
	{% for vr in model_vr %}
          <option value="{{vr.id}}">{{vr.type_name}}</option>
	{% endfor %}
	</select><br>
	</select><br>
   <select class="multiselect" multiple="multiple" name="name_var">
	{% for vrc in model_com %}
          <option value="{{vrc.name}}">{{vrc.name}}</option>
	{% endfor %}
	</select>
	   
  <br>
	<label>Вероятность:</label>
	<input name="p" type="text" value="{{ form.p}}">
	<label>Проект:</label>
	<select name="var_project">
	{% for var_proj in model_proj %}
          <option value="{{var_proj.id}}">{{var_proj.title}}</option>
	{% endfor %}
	</select>
	<br>
	<br>
        <input class="btn info"  type="submit" value="Отправить"></form>
    </form>
  </TH>
  <TH ALIGN=CENTER>
	</TH>
 </TR>
</TABLE>
<TABLE>
<CAPTION>Variants</CAPTION>
<TR>
<TH width=100>Имя компонента    </TH>
<TH width=30>  Тип    </TH>
<TH width=30>  Вероятность   </TH>
<TH width=30>   </TH>
</TR>
{% for variants in model_var_v %}
<TR>
<TD width=30> {{variants.num}}</TD>
<TD ALIGN=CENTER >{{variants.type_c.type_name}}</TD>
<TD>{{variants.pvar}}</TD>	
<TD>  <a href="{% url 'delete_var' variants.id %}"> <span class="label label-important">удалить</span> </a></TD>
</TR>
{% endfor %}
</TABLE>
 
 </TR>
</TABLE>


<a href="{% url 'list1' %}"><span class="label label-success">Вернуться к проектам</splan></a>
{% endblock %}